{% set name = "openkim-models" %}
{% set version = "2021.01.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://s3.openkim.org/archives/collection/{{ name }}-{{ version|replace('.', '-') }}.txz
  sha256: 8824adee02ae4583bd378cc81140fbb49515c5965708ee98d856d122d48dd95f

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - vim
  host:
    - kim-api >=2.2.1
  run:
    - kim-api >=2.2.1

test:
  commands:
    - kim-api-collections-management list

about:
  home: https://openkim.org
  license: CDDL-1.0
  license_family: OTHER
  license_file: {{ name }}-{{ version|replace('.', '-') }}/LICENSE
  summary: 'All OpenKIM Models compatible with kim-api'

  description: |
    All OpenKIM Models compatible with kim-api.
  doc_url: https://openkim.org/doc/usage/obtaining-models/
  dev_url: https://openkim.org

extra:
  recipe-maintainers:
    - brendonwaters
    - jan-janssen
    - ellio167
